# Generated by Django 5.0.1 on 2024-05-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
